### ISSUE TITLE
Question about "Ld_value" and configuration

### ISSUE THREAD

**Issue by AlKitChung** [TimSong412/2D-surfel-gaussian#9]
Hi! Thank you for sharing the code. I attempted to train it using the Dr. Johnson dataset, but encountered an error."
[ITER 1000] Evaluating train: L1 0.07388863191008568 PSNR 19.659012985229495 [02/05 16:00:35]
Traceback (most recent call last):
  File "train.py", line 328, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "train.py", line 189, in training
    training_report(tb_writer, iteration, Ll1, Ln, loss, l1_loss, iter_start.elapsed_time(iter_end), testing_iterations, scene, render, (pipe, background), Ld_value/(viewpoint_cam.image_height * viewpoint_cam.image_width), gradnorm)
  File "train.py", line 298, in training_report
    tb_writer.add_histogram("scene/opacity_histogram", scene.gaussians.get_opacity, iteration)
  File "/home/xxxx/anaconda3/envs/gs/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 485, in add_histogram
    histogram(tag, values, bins, max_bins=max_bins), global_step, walltime
  File "/home/xxxx/anaconda3/envs/gs/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 358, in histogram
    hist = make_histogram(values.astype(float), bins, max_bins)
  File "/home/xxxx/anaconda3/envs/gs/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 386, in make_histogram
    cum_counts = np.cumsum(np.greater(counts, 0, dtype=np.int32))
TypeError: No loop matching the specified signature and casting was found for ufunc greater
Could you provide some additional guidelines on adjusting the weights and configuration settings?

**Comment by TimSong412** [comment]
It seems to be the problem of "add_histogram". Would you please try removing this line? We didn't run into this problem before.
